---
vagrantfile-local:
    vm:
        box: ubuntu-precise12042-x64-vbox43
        box_url: 'http://box.puphpet.com/ubuntu-precise12042-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.56.142
            forwarded_port:
                CocLsFE7aIwA:
                    host: '8081'
                    guest: '80'
                CocLsFE7aIwE:
                    host: '8083'
                    guest: '3306'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '1024'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            lxc:
                box: fgrehm/precise64-lxc
                box_url: https://atlas.hashicorp.com/fgrehm/boxes/precise64-lxc/versions/1.2.0/providers/lxc.box
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            - id: drupal
              source: ./
              target: /var/www
              nfs: 'true'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
