---
- name: Install Compass & Susy
  gem: name={{ item.value.name }} version={{ item.value.version }}
#  gem: >
#    name: {{ item.value.name }}
#    version: {{ item.value.version }}
  with_dict: gems